CREATE TABLE IF NOT EXISTS users (
   id CHAR(100) PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   emailVerified DATETIME NULL,
   image VARCHAR(500) NULL,
   hashedPassword VARCHAR(255) NOT NULL,
   role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id CHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    list DECIMAL(10,2),
    brand VARCHAR(100),
    category VARCHAR(100),
    inStock BOOLEAN DEFAULT TRUE
);