CREATE TABLE IF NOT EXISTS orders (
    id CHAR(100) PRIMARY KEY,
    userId CHAR(100) NOT NULL,
    amount DECIMAL(10, 2) DEFAULT 0.00,
    currency VARCHAR(10),
    status VARCHAR(50),
    deliveryStatus VARCHAR(50),
    paymentIntentId VARCHAR(255) NOT NULL,
    products JSON NOT NULL,
    address JSON NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id CHAR(100) PRIMARY KEY,
    userId CHAR(100) NOT NULL,
    accountType VARCHAR(100) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    providerAccountId VARCHAR(255) NOT NULL,
    refreshToken TEXT,
    accessToken TEXT,
    expiresAt BIGINT,
    tokenType VARCHAR(50),
    scope VARCHAR(255),
    idToken TEXT,
    sessionState VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    id CHAR(100) PRIMARY KEY,
    userId CHAR(100) NOT NULL,
    productId CHAR(100) NOT NULL,
    rating VARCHAR(10) NOT NULL,
    comment TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS images (
    id CHAR(100) PRIMARY KEY,
    color VARCHAR(100) NOT NULL,
    colorCode VARCHAR(50) NOT NULL,
    image TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

